#!/usr/bin/env bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$BASEDIR"/_common-setup.sh

if [ "$EUID" == "0" ]; then
  die "Please do not run this script as root"
fi

SKIP_POST_INSTALL=false
UPDATE=false
SHOW_HELP=false
VERBOSE=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --update|-u)
    UPDATE=true
    shift
    ;;
    --help|-h)
    SHOW_HELP=true
    break
    ;;
    --verbose)
    VERBOSE=true
    shift
    ;;
    --skip-post-install|-s)
    SKIP_POST_INSTALL=true
    shift
    ;;
    *)
    shift
    ;;
  esac
done
eval set -- "$PARSED_ARGS"

if $SHOW_HELP; then
  cat <<EOF
Dotfiles installer.

Usage:
  `readlink -f "$0"` [flags]

Flags:
  -c, --clean              Will clean installed packages.
  -u, --update             Will download and install/reinstall even if the tools are already installed
      --verbose            Show verbose output
      --skip-post-install  Will skip post install steps (installation of packages etc)
      --gh <user:pw>       GitHub username and password
  -h, --help               This help
EOF
  exit 0
fi

if $VERBOSE; then
  writeGreen "Running `basename "$0"` $ALL_ARGS"
  writeGreen "  Update is $UPDATE"
  writeGreen "  Skip post install is $SKIP_POST_INSTALL"
fi

pushd "${BASEDIR}" > /dev/null

export DEBIAN_FRONTEND=noninteractive
if grep microsoft /proc/version -q; then
  export WSL=true
else
  export WSL=false
fi
if [ -f /.dockerenv ] || grep docker /proc/1/cgroup -qa 2> /dev/null; then
  export RUNNING_IN_CONTAINER=true
else
  export RUNNING_IN_CONTAINER=false
fi
sudo -E "$BASEDIR"/pre-install.sh "$@"
"$BASEDIR"/install.sh "$@"
if ! $SKIP_POST_INSTALL; then
  "$BASEDIR"/post-install.sh "$@"
fi

popd > /dev/null

echo Done.
