#!/usr/bin/env bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/scripts"
# shellcheck disable=SC1091
source "$BASEDIR"/_common-setup.sh

if [ "$EUID" == "0" ]; then
  die "Please do not run this script as root"
fi

UPDATE=false
SHOW_HELP=false
VERBOSE=false
while [[ $# -gt 0 ]]; do
  case "$1" in
  --update | -u)
    UPDATE=true
    shift
    ;;
  --help | -h)
    SHOW_HELP=true
    break
    ;;
  --verbose)
    VERBOSE=true
    shift
    ;;
  *)
    shift
    ;;
  esac
done
eval set -- "$PARSED_ARGS"

if $SHOW_HELP; then
  cat <<EOF
Dotfiles installer.

Usage:
  $(readlink -f "$0") [flags]

Flags:
  -c, --clean              Will clean installed packages.
  -u, --update             Will download and install/reinstall even if the tools are already installed
      --verbose            Show verbose output
      --gh <user:pw>       GitHub username and password
  -h, --help               This help
EOF
  exit 0
fi

if $VERBOSE; then
  writeGreen "Running $(basename "$0") $ALL_ARGS"
  writeGreen "  Update is $UPDATE"
fi

sudo -E "$BASEDIR"/pre-install.sh "$@"
"$BASEDIR"/install.sh "$@"

echo Done.
