name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "*"
    paths-ignore:
      - "*.md"
      - "*.txt"
      - "*.yml"
      - .editorconfig
      - ".github/**"
      - .gitignore
      - .gitattributes
  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "*.txt"
      - "*.yml"
      - .editorconfig
      - ".github/**"
      - .gitignore
      - .gitattributes
jobs:
  build:
    name: Build
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Shellcheck
        uses: https://github.com/ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: --shell bash
        with:
          ignore_paths: ./.testsupport/* ./.git/*
