# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
---
# add completers to kubecolor to be equal to those from kubectl
name: kubecolor
description: Colorize your kubectl output
completion:
  positionalany: ["$carapace.bridge.CarapaceBin([kubectl])"]
