# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
---
# add completers to home-manager
name: home-manager
description: Nix home-manager
flags:
  -f?=: The home configuration file. Default is '~/.config/nixpkgs/home.nix'.
  -A?=: Optional attribute that selects a configuration expression in the configuration file.
  -I?=: Add a path to the Nix expression search path.
  --flake?=: Use Home Manager configuration at flake-uri Default is '~/.config/home-manager'.
  -b?=: Move existing files to new path rather than fail.
  -v?: Verbose output
  -n?: Do a dry run, only prints what actions would be taken
  --version?: Print the Home Manager version
  --arg*: Override inputs passed to home-manager.nix
  --cores?=: ""
  --debug?: ""
  --impure?: ""
  --keep-failed?: ""
  --keep-going?: ""
  -j, --max-jobs?=: ""
  --option?=: ""
  -L, --print-build-logs?: ""
  --show-trace?: ""
  --substitute?: ""
  --no-substitute?: ""
  --no-out-link?: Do not create a symlink to the output path
  --no-write-lock-file?: ""
  --builders?=: ""
  --refresh?: "Consider all previously downloaded files out-of-date"
persistentflags:
  -h, --help: Print this help
commands:
- name: help
  description: Print this help
- name: edit
  description: Open the home configuration in $VISUAL or $EDITOR
- name: option
  description: Inspect configuration option named OPTION.NAME.
- name: build
  description: Build configuration into result directory
- name: init
  description: Initializes a configuration in the given directory. If the directory does not exist, then it will be created. The default directory is '~/.config/home-manager'.
  flags:
    --switch?: Immediately activate the generated configuration.
  completion:
    positional:
      - ["$carapace.fs.SubDirectories"]
- name: instantiate
  description: Instantiate the configuration and print the resulting derivation
- name: switch
  description: Build and activate configuration
- name: generations
  description: List all home environment generations
- name: remove-generations
  description: Remove indicated generations. Use 'generations' command to find suitable generation numbers.
- name: expire-generations
  description: Remove generations older than TIMESTAMP where TIMESTAMP is interpreted as in the -d argument of the date tool. For example "-30 days" or "2018-01-01".
- name: packages
  description: List all packages installed in home-manager-path
- name: news
  description: Show news entries in a pager
- name: uninstall
  description: Remove Home Manager
