# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
---
# add completers to hub to be equal to those from git, so that git aliased to hub works
name: hub
description: Github's helper
completion:
  positionalany: ["$carapace.bridge.CarapaceBin([git])"]
