{
  imports = [
    ./apps/psensor.nix
    ./org/gnome/desktop/applications/terminal.nix
    ./org/gnome/desktop/datetime.nix
    ./org/gnome/desktop/interface.nix
    ./org/gnome/desktop/input-sources.nix
    ./org/gnome/desktop/peripherals/mouse.nix
    ./org/gnome/desktop/wm/keybindings.nix
    ./org/gnome/shell/extensions/blur-my-shell.nix
    ./org/gnome/shell/extensions/burn-my-windows.nix
    ./org/gnome/shell/extensions/caffeine.nix
    ./org/gnome/shell/extensions/clipboard-history.nix
    ./org/gnome/shell/extensions/com/github/hermes83/compiz-windows-effect.nix
    ./org/gnome/shell/extensions/dash-to-dock.nix
    ./org/gnome/shell/extensions/desktop-cube.nix
    ./org/gnome/shell/extensions/flypie.nix
    ./org/gnome/shell/extensions/freon.nix
    ./org/gnome/shell/extensions/hibernate-status-button.nix
    ./org/gnome/shell/extensions/ncom/github/hermes83/compiz-alike-magic-lamp-effect.nix
    ./org/gnome/shell/extensions/wsmatrix.nix
    ./org/gnome/shell/keybindings.nix
    ./org/gnome/settings-daemon/plugins.nix
    ./desktop/ibus/panel/emoji.nix
  ];
}
