version: 7
profiles:
  - name: nushell
    icon: fas fa-terminal
    options:
      command: /home/giggio/.nix-profile/bin/nu
      env: {}
      args: []
    id: local:custom:nushell:a408301a-1276-43a4-bdd6-a90d055b64d5
    type: local
  - icon: fas fa-terminal
    options:
      command: /home/giggio/.dotnet/tools/pwsh
      env:
        DOTNET_ROOT: /nix/store/6lz1grv5cqmmi1d52m0vy26lj35zilh5-dotnet-core-combined
      args: []
    name: pwsh
    id: local:custom:pwsh:a998b1be-6e97-4d62-afe5-1c2bfc15f295
    behaviorOnSessionEnd: keep
    type: local
  - name: bash (noprofile)
    icon: fas fa-terminal
    options:
      command: /usr/bin/bash
      args:
        - '--noprofile'
        - '--norc'
      env: {}
    type: local
    id: local:custom:bash-(noprofile):89841a3e-6192-4b89-8be1-67c6313fc5fe
groups: []
configSync:
  parts: {}
hotkeys:
  toggle-window: []
  copy-current-path: []
  ctrl-c:
    - Ctrl-C
  copy:
    - Ctrl-Shift-C
  paste:
    - Ctrl-Shift-V
    - Shift-Insert
  select-all:
    - Ctrl-Shift-A
  clear: []
  zoom-in:
    - Ctrl-=
    - Ctrl-Shift-=
  zoom-out:
    - Ctrl--
    - Ctrl-Shift--
  reset-zoom:
    - Ctrl-0
  home:
    - Home
  end:
    - End
  previous-word:
    - Ctrl-Left
  next-word:
    - Ctrl-Right
  delete-previous-word:
    - Ctrl-Backspace
  delete-line:
    - Ctrl-Shift-Backspace
  delete-next-word:
    - Ctrl-Delete
  search:
    - Ctrl-Shift-F
  pane-focus-all:
    - Ctrl-Shift-I
  focus-all-tabs:
    - Ctrl-Alt-Shift-I
  scroll-to-top:
    - Ctrl-PageUp
  scroll-up:
    - Alt-PageUp
  scroll-down:
    - Alt-PageDown
  scroll-to-bottom:
    - Ctrl-PageDown
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings-tab: {}
  settings:
    - Ctrl-,
  serial:
    - Alt-K
  restart-serial-session: []
  new-tab:
    - Ctrl-Shift-T
  new-window:
    - Ctrl-Shift-N
  profile:
    local:usrbinbash:
      - Ctrl-Shift-Y
  profile-selectors: {}
  toggle-fullscreen:
    - F11
  close-tab:
    - Ctrl-Shift-W
  reopen-tab:
    - Ctrl-Shift-Z
  rename-tab:
    - Ctrl-Shift-R
  previous-tab:
    - Ctrl-Shift-Left
    - Ctrl-Shift-Tab
  move-tab-left:
    - Ctrl-Shift-PageUp
  move-tab-right:
    - Ctrl-Shift-PageDown
  rearrange-panes:
    - Ctrl-Shift
  duplicate-tab: []
  restart-tab: []
  reconnect-tab: []
  disconnect-tab: []
  explode-tab:
    - Ctrl-Shift-.
  combine-tabs:
    - Ctrl-Shift-,
  tab-1:
    - Alt-1
  tab-2:
    - Alt-2
  tab-3:
    - Alt-3
  tab-4:
    - Alt-4
  tab-5:
    - Alt-5
  tab-6:
    - Alt-6
  tab-7:
    - Alt-7
  tab-8:
    - Alt-8
  tab-9:
    - Alt-9
  tab-10:
    - Alt-0
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - Ctrl-Shift-S
  split-bottom:
    - Ctrl-Shift-D
  split-left: []
  split-top: []
  pane-nav-right:
    - Ctrl-Alt-Right
  pane-nav-down:
    - Ctrl-Alt-Down
  pane-nav-up:
    - Ctrl-Alt-Up
  pane-nav-left:
    - Ctrl-Alt-Left
  pane-nav-previous:
    - Ctrl-Alt-[
  pane-nav-next:
    - Ctrl-Alt-]
  pane-nav-1: []
  pane-nav-2: []
  pane-nav-3: []
  pane-nav-4: []
  pane-nav-5: []
  pane-nav-6: []
  pane-nav-7: []
  pane-nav-8: []
  pane-nav-9: []
  pane-maximize:
    - Ctrl-Alt-Enter
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  close-pane: []
  switch-profile:
    - Ctrl-Alt-T
  profile-selector:
    - Ctrl-Shift-E
  command-selector:
    - Ctrl-Shift-P
  next-tab:
    - Ctrl-Shift-Right
    - Ctrl-Tab
  toggle-last-tab:
    - Ctrl-Escape
terminal:
  searchOptions: {}
  colorScheme:
    name: Ubuntu
    foreground: '#eeeeec'
    background: '#300a24'
    cursor: '#bbbbbb'
    colors:
      - '#2e3436'
      - '#cc0000'
      - '#4e9a06'
      - '#c4a000'
      - '#3465a4'
      - '#75507b'
      - '#06989a'
      - '#d3d7cf'
      - '#555753'
      - '#ef2929'
      - '#8ae234'
      - '#fce94f'
      - '#729fcf'
      - '#ad7fa8'
      - '#34e2e2'
      - '#eeeeec'
  customColorSchemes: []
  font: CaskaydiaCove Nerd Font Mono
  ligatures: true
  fontSize: 16
  profile: local:custom:nushell:a408301a-1276-43a4-bdd6-a90d055b64d5
  showTabProfileIcon: true
  frontend: xterm
ssh: {}
clickableLinks: {}
accessibility: {}
appearance:
  lastTabClosesWindow: true
  tabsInFullscreen: true
hacks: {}
providerBlacklist: []
commandBlacklist: []
enableAnalytics: false
enableWelcomeTab: false
pluginBlacklist: []
profileDefaults:
  ssh:
    disableDynamicTitle: true
  local:
    type: local
    options:
      env: {}
profileBlacklist:
  - serial:port-devttyS0
  - serial:port-devttyS1
  - serial:port-devttyS2
  - serial:port-devttyS3
  - serial:port-devttyS4
  - serial:port-devttyS5
  - serial:port-devttyS6
  - serial:port-devttyS7
  - serial:port-devttyS8
  - serial:port-devttyS9
  - serial:port-devttyS10
  - serial:port-devttyS11
  - serial:port-devttyS12
  - serial:port-devttyS13
  - serial:port-devttyS14
  - serial:port-devttyS15
  - serial:port-devttyS16
  - serial:port-devttyS17
  - serial:port-devttyS18
  - serial:port-devttyS19
  - serial:port-devttyS20
  - serial:port-devttyS21
  - serial:port-devttyS22
  - serial:port-devttyS23
  - serial:port-devttyS24
  - serial:port-devttyS25
  - serial:port-devttyS26
  - serial:port-devttyS27
  - serial:port-devttyS28
  - serial:port-devttyS29
  - serial:port-devttyS30
  - serial:port-devttyS31
  - local:binbash
  - local:binrbash
  - local:usrbinrbash
  - local:usrbinscreen
  - serial:template
  - local:binsh
  - local:usrbindash
  - local:default
recoverTabs: false
