"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$mise\
$crystal\
$custom\
"""

[character]
success_symbol = "[❯](bold green)"

[directory]
truncate_to_repo = false
truncation_length = 12
truncation_symbol = "…/"

[kubernetes]
disabled = true
symbol = "⎈ "

[git_branch]
only_attached = true

[git_commit]
format = "[ \\($hash\\)]($style) [\\($tag\\)]($style) "
tag_disabled = false
tag_symbol = "🔖"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "bold purple"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
untracked = "🤷${count}"
modified = "📝${count}"
deleted = "${count}"
staged = "➕${count}"

[git_metrics]
disabled = false

[status]
disabled = false
map_symbol = true

[time]
disabled = false

[sudo]
disabled = false
symbol = "!"
format = "[$symbol]($style)"
style = "bold red"

[dotnet]
symbol = " "
format = "[$symbol($version )(with $tfm )]($style)"

[nix_shell]
format = "via [$symbol$name]($style) "
symbol = "❄ "
