name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "*"
    paths-ignore:
      - "*.md"
      - "*.txt"
      - "*.yml"
      - .editorconfig
      - ".github/**"
      - .gitignore
      - .gitattributes
  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "*.txt"
      - "*.yml"
      - .editorconfig
      - ".github/**"
      - .gitignore
      - .gitattributes

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'github-check' }}
          path: "."
          pattern: |
            *.sh
            *.bash
          exclude: |
            ./.testsupport/*
            ./.git/*
          check_all_files_with_shebangs: true
          shellcheck_flags: --shell bash
          fail_on_error: true
